import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Shared Content - EngagePerfect AI',
  description: 'Caption generated by EngagePerfect AI',
  openGraph: {
    title: 'EngagePerfect AI Caption',
    description: 'Create engaging captions for your social media with AI assistance',
    url: 'https://engageperfect.com/share',
    siteName: 'EngagePerfect',
    images: [
      {
        url: 'https://engageperfect.com/og-image.jpg',
        width: 1200,
        height: 630,
        alt: 'EngagePerfect AI',
      },
    ],
    locale: 'en_US',
    type: 'website',
  },
  twitter: {
    card: 'summary_large_image',
    title: 'EngagePerfect AI Caption',
    description: 'Create engaging captions for your social media with AI assistance',
    images: ['https://engageperfect.com/og-image.jpg'],
  },
};

export default function ShareLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}